### ISSUE TITLE
Daily Motion

### ISSUE THREAD

**Issue by unlocKing** [beardypig/plugin.video.streamlink#1]
Having an issue with the dailymotion plugin through Kodi, but works via CLI and VLC:

15:47:46 T:9392  NOTICE: --- Playing "FTV". plugin://plugin.video.streamlink/play?url=http://www.dailymotion.com/video/x3m6nld
15:47:48 T:27448   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'streamlink.exceptions.PluginError'>
                                            Error Contents: Unable to parse manifest XML: 'NoneType' object is not callable ('<?xml version="1.0" encoding="utf- ...)
                                            Traceback (most recent call last):
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\addon.py", line 85, in <module>
                                                plugin.run()
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\simpleplugin.py", line 779, in run
                                                result = action_callable(params)
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\addon.py", line 56, in root
                                                streams = session.streams(url)
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\lib\streamlink\session.py", line 424, in streams
                                                return plugin.streams(**params)
                                              File "C:\Users\j\AppData\Roaming\Kodi\addons\plugin.video.streamlink\lib\streamlink\plugin\plugin.py", line 246, in streams
                                                raise PluginError(err)
                                            PluginError: Unable to parse manifest XML: 'NoneType' object is not callable ('<?xml version="1.0" encoding="utf- ...)
                                            -->End of Python script error report<--

This was through playlist loader. 

Any ideas? 

Thanks.

**Comment by beardypig** [comment]
Could possibly be an issue with the different xml parsers in the different versions of Kodi. Which version of Kodi are you using?

**Comment by unlocKing** [comment]
16.1

I tested the ustream plugin and that worked

**Comment by beardypig** [comment]
Are you able to test it with Kodi 17?

**Comment by unlocKing** [comment]
yea, i can setup a VM in about half hour

**Comment by unlocKing** [comment]
Errors:


18:36:02.550 T:1128 WARNING: <urlopen error unknown url type: plugin>
18:36:02.550 T:1128  NOTICE: --- Playing "ftv". plugin://plugin.video.streamlink/play?url=http://www.dailymotion.com/video/x3m6nld
18:36:04.683 T:3204   ERROR: 127.0.0.1 - - [17/May/2017 18:36:04] code 404, message File not found
18:36:04.683 T:3204   ERROR: 127.0.0.1 - - [17/May/2017 18:36:04] "HEAD /proxy/a3c20671b5864fc79f293f43bafa3f9f HTTP/1.1" 404 -
18:36:04.697 T:2440  NOTICE: VideoPlayer: Opening: http://localhost:6531/proxy/a3c20671b5864fc79f293f43bafa3f9f
18:36:04.698 T:2440 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
18:36:04.903 T:3204   ERROR: 127.0.0.1 - - [17/May/2017 18:36:04] code 404, message File not found
18:36:04.903 T:3204   ERROR: 127.0.0.1 - - [17/May/2017 18:36:04] "HEAD /proxy/a3c20671b5864fc79f293f43bafa3f9f HTTP/1.1" 404 -
18:36:04.905 T:2440   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 104 for 1.
18:36:04.905 T:2440   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
18:36:04.906 T:1572  NOTICE: Creating InputStream
18:36:05.109 T:3204   ERROR: Traceback (most recent call last):
18:36:05.110 T:3204   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 295, in _handle_request_noblock
18:36:05.113 T:3204   ERROR:     self.process_request(request, client_address)
18:36:05.113 T:3204   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 321, in process_request
18:36:05.114 T:3204   ERROR:     self.finish_request(request, client_address)
18:36:05.114 T:3204   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 334, in finish_request
18:36:05.114 T:3204   ERROR:     self.RequestHandlerClass(request, client_address, self)
18:36:05.114 T:3204   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 655, in __init__
18:36:05.114 T:3204   ERROR:     self.handle()
18:36:05.114 T:3204   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\BaseHTTPServer.py", line 340, in handle
18:36:05.116 T:3204   ERROR:     self.handle_one_request()
18:36:05.116 T:3204   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\BaseHTTPServer.py", line 328, in handle_one_request
18:36:05.116 T:3204   ERROR:     method()
18:36:05.116 T:3204   ERROR:   File "C:\Users\W7\AppData\Roaming\Kodi\addons\plugin.video.streamlink\service.py", line 25, in do_GET
18:36:05.116 T:3204   ERROR:     session = streamlink.Streamlink()
18:36:05.116 T:3204   ERROR: NameError: global name 'streamlink' is not defined
18:36:05.117 T:1572   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
18:36:05.117 T:1572   ERROR: CCurlFile::Open failed with code 0 for http://localhost:6531/proxy/a3c20671b5864fc79f293f43bafa3f9f
18:36:05.323 T:3204   ERROR: Traceback (most recent call last):
18:36:05.323 T:3204   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 295, in _handle_request_noblock
18:36:05.324 T:3204   ERROR:     self.process_request(request, client_address)
18:36:05.324 T:3204   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 321, in process_request
18:36:05.324 T:3204   ERROR:     self.finish_request(request, client_address)
18:36:05.324 T:3204   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 334, in finish_request
18:36:05.324 T:3204   ERROR:     self.RequestHandlerClass(request, client_address, self)
18:36:05.324 T:3204   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\SocketServer.py", line 655, in __init__
18:36:05.324 T:3204   ERROR:     self.handle()
18:36:05.324 T:3204   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\BaseHTTPServer.py", line 340, in handle
18:36:05.324 T:3204   ERROR:     self.handle_one_request()
18:36:05.325 T:3204   ERROR:   File "C:\Program Files\Kodi\system\python\Lib\BaseHTTPServer.py", line 328, in handle_one_request
18:36:05.325 T:3204   ERROR:     method()
18:36:05.325 T:3204   ERROR:   File "C:\Users\W7\AppData\Roaming\Kodi\addons\plugin.video.streamlink\service.py", line 25, in do_GET
18:36:05.325 T:3204   ERROR:     session = streamlink.Streamlink()
18:36:05.325 T:3204   ERROR: NameError: global name 'streamlink' is not defined
18:36:05.326 T:1572   ERROR: CCurlFile::FillBuffer - Failed: Server returned nothing (no headers, no data)(52)
18:36:05.326 T:1572   ERROR: CCurlFile::Open failed with code 0 for http://localhost:6531/proxy/a3c20671b5864fc79f293f43bafa3f9f
18:36:05.326 T:1572   ERROR: XFILE::CFileCache::Open - failed to open source <http://localhost:6531/proxy/a3c20671b5864fc79f293f43bafa3f9f>
18:36:05.326 T:1572   ERROR: CVideoPlayer::OpenInputStream - error opening [http://localhost:6531/proxy/a3c20671b5864fc79f293f43bafa3f9f]
18:36:05.326 T:1572  NOTICE: CVideoPlayer::OnExit()
18:36:05.326 T:2440   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.playlistLoader/?logos=&move=0&mode=32&index=0&url=plugin%3A%2F%2Fplugin.video.streamlink%2Fplay%3Furl%3Dhttp%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx3m6nld&iconimage=&cache=0&name=ftv]
18:36:05.330 T:2440  NOTICE: CVideoPlayer::CloseFile()
18:36:05.330 T:2440  NOTICE: VideoPlayer: waiting for threads to exit
18:36:05.330 T:2440  NOTICE: VideoPlayer: finished waiting
18:36:05.330 T:2440  NOTICE: CVideoPlayer::CloseFile()
18:36:05.330 T:2440  NOTICE: VideoPlayer: waiting for threads to exit
18:36:05.330 T:2440  NOTICE: VideoPlayer: finished waiting
18:36:05.382 T:2396 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.playlistLoader/?logos=&move=0&mode=32&index=0&url=plugin%3A%2F%2Fplugin.video.streamlink%2Fplay%3Furl%3Dhttp%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx3m6nld&iconimage=&cache=0&name=ftv
18:36:05.382 T:2396   ERROR: InputStream: Error opening, plugin://plugin.video.playlistLoader/?logos=&move=0&mode=32&index=0&url=plugin%3A%2F%2Fplugin.video.streamlink%2Fplay%3Furl%3Dhttp%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx3m6nld&iconimage=&cache=0&name=ftv

**Comment by beardypig** [comment]
I have reproduced the error, and I am working on a fix... I have a fix, I will release it so you can test it and I will keep working on it.

**Comment by unlocKing** [comment]
Yea, I'm here for another half hour then back in 3 hours after that.

Thanks.

**Comment by beardypig** [comment]
I have released a new version that should resolve the issue, it's not 100% but it should work for you. I will continue to work on it and update this issue once it has been resolved to my satisfaction :)

**Comment by unlocKing** [comment]
Many thanks, worked after send run :)

Here's the log in case it's not something you're aware of:

```
20:00:49 T:32848 WARNING: <urlopen error unknown url type: plugin>
20:00:49 T:32848  NOTICE: --- Playing "bristol". plugin://plugin.video.streamlink/play?url=http%3A%2F%2Fwww.dailymotion.com%2Fvideo%2Fx5ev84u
20:00:51 T:30964   ERROR: 127.0.0.1 - - [17/May/2017 20:00:51] code 404, message File not found
20:00:51 T:30964   ERROR: 127.0.0.1 - - [17/May/2017 20:00:51] "HEAD /proxy/699b0dc0676a4368957039ddfd8b310a HTTP/1.1" 404 -
20:00:51 T:30964   ERROR: Traceback (most recent call last):
20:00:51 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 295, in _handle_request_noblock
20:00:51 T:30964   ERROR:     self.process_request(request, client_address)
20:00:51 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 321, in process_request
20:00:51 T:30964   ERROR:     self.finish_request(request, client_address)
20:00:51 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 334, in finish_request
20:00:51 T:30964   ERROR:     self.RequestHandlerClass(request, client_address, self)
20:00:51 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 653, in __init__
20:00:51 T:30964   ERROR:     self.finish()
20:00:51 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 712, in finish
20:00:51 T:30964   ERROR:     self.wfile.close()
20:00:51 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\socket.py", line 279, in close
20:00:51 T:30964   ERROR:     self.flush()
20:00:51 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\socket.py", line 303, in flush
20:00:51 T:30964   ERROR:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
20:00:51 T:30964   ERROR: error: [Errno 10054] An existing connection was forcibly closed by the remote host
20:00:51 T:3904  NOTICE: DVDPlayer: Opening: http://localhost:6531/proxy/699b0dc0676a4368957039ddfd8b310a
20:00:51 T:3904 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
20:00:51 T:32852  NOTICE: Creating InputStream
20:00:51 T:30964   ERROR: 127.0.0.1 - - [17/May/2017 20:00:51] code 404, message File not found
20:00:51 T:30964   ERROR: 127.0.0.1 - - [17/May/2017 20:00:51] "HEAD /proxy/699b0dc0676a4368957039ddfd8b310a HTTP/1.1" 404 -
20:00:52 T:30964   ERROR: 127.0.0.1 - - [17/May/2017 20:00:52] "GET /proxy/699b0dc0676a4368957039ddfd8b310a HTTP/1.1" 200 -
20:00:52 T:32852  NOTICE: Creating Demuxer
20:00:52 T:32852  NOTICE: Opening stream: 0 source: 256
20:00:52 T:32852  NOTICE: Creating video codec with codec id: 28
20:00:52 T:32852  NOTICE: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
20:00:52 T:32852  NOTICE: Creating video thread
20:00:52 T:32852  NOTICE: Opening stream: 1 source: 256
20:00:52 T:32852  NOTICE: Finding audio codec for: 86018
20:00:52 T:32172  NOTICE: running thread: video_thread
20:00:52 T:32852  NOTICE: Creating audio thread
20:00:52 T:32172  NOTICE: CDVDVideoCodecFFmpeg::GetFormat - Creating DXVA(1040x576)
20:00:52 T:31568  NOTICE: running thread: CDVDPlayerAudio::Process()
20:00:52 T:31568  NOTICE: Creating audio stream (codec id: 86018, channels: 2, sample rate: 44100, no pass-through)
20:00:52 T:32172  NOTICE:  fps: 25.000000, pwidth: 1040, pheight: 576, dwidth: 1040, dheight: 576
20:00:52 T:32172  NOTICE: Display resolution ADJUST : 1920x1080@ 50.00 - Full Screen (68) (weight: 0.000)
20:00:52 T:32172  NOTICE: D3D: rendering method forced to DXVA processor
20:00:52 T:32172  NOTICE: DXVA::CProcessorHD::InitProcessor - Supported deinterlace methods: Blend:yes, Bob:yes, Adaptive:yes, MoComp:no.
20:00:52 T:3904 WARNING: CWinRenderer::UpdateVideoFilter - chosen scaling method 1 is not supported by renderer
20:00:52 T:6384  NOTICE: Stream All The Sources: Service: Playback started
20:00:53 T:31568  NOTICE: CDVDPlayerAudio::OutputPacket skipping a packets of duration 46
20:01:01 T:3904  NOTICE: CDVDPlayer::CloseFile()
20:01:01 T:3904  NOTICE: DVDPlayer: waiting for threads to exit
20:01:02 T:32172 WARNING: CRenderManager::WaitForBuffer - timeout waiting for buffer
20:01:05 T:32852 WARNING: Previous line repeats 2 times.
20:01:05 T:32852  NOTICE: CDVDPlayer::OnExit()
20:01:05 T:32852  NOTICE: Closing stream player 1
20:01:05 T:32852  NOTICE: Waiting for audio thread to exit
20:01:05 T:31568  NOTICE: thread end: CDVDPlayerAudio::OnExit()
20:01:05 T:32852  NOTICE: Closing audio device
20:01:05 T:32852  NOTICE: Deleting audio codec
20:01:05 T:32852  NOTICE: Closing stream player 2
20:01:05 T:32852  NOTICE: waiting for video thread to exit
20:01:05 T:32172  NOTICE: thread end: video_thread
20:01:05 T:32852  NOTICE: deleting video codec
20:01:05 T:32852  NOTICE: DXVA::CDecoder::Close - closing decoder
20:01:05 T:32852  NOTICE: DXVA::Close - closing decoder context
20:01:08 T:3904  NOTICE: DVDPlayer: finished waiting
20:01:08 T:6384  NOTICE: Stream All The Sources: Service: Playback Stopped
20:01:08 T:3904  NOTICE: CDVDPlayer::CloseFile()
20:01:08 T:3904  NOTICE: DVDPlayer: waiting for threads to exit
20:01:08 T:3904  NOTICE: DVDPlayer: finished waiting
20:01:08 T:3904  NOTICE: CDVDPlayer::CloseFile()
20:01:08 T:3904  NOTICE: DVDPlayer: waiting for threads to exit
20:01:08 T:3904  NOTICE: DVDPlayer: finished waiting
20:01:08 T:3904   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
20:01:09 T:30964   ERROR: Traceback (most recent call last):
20:01:09 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 295, in _handle_request_noblock
20:01:09 T:30964   ERROR:     self.process_request(request, client_address)
20:01:09 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 321, in process_request
20:01:09 T:30964   ERROR:     self.finish_request(request, client_address)
20:01:09 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 334, in finish_request
20:01:09 T:30964   ERROR:     self.RequestHandlerClass(request, client_address, self)
20:01:09 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 653, in __init__
20:01:09 T:30964   ERROR:     self.finish()
20:01:09 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\SocketServer.py", line 712, in finish
20:01:09 T:30964   ERROR:     self.wfile.close()
20:01:09 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\socket.py", line 279, in close
20:01:09 T:30964   ERROR:     self.flush()
20:01:09 T:30964   ERROR:   File "C:\Program Files (x86)\Kodi\system\python\Lib\socket.py", line 303, in flush
20:01:09 T:30964   ERROR:     self._sock.sendall(view[write_offset:write_offset+buffer_size])
20:01:09 T:30964   ERROR: error: [Errno 10054] An existing connection was forcibly closed by the remote host
```

If you need any further tests let me know or feel free to close this.

Cheers!
